# Configuration file for CGMacros CCR Prediction Project
# IEEE BHI 2025 Track 2 Challenge

# Data Configuration
DATA_CONFIG:
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  cgmacros_dir: "Dataset/CGMacros_CSVs"
  supplementary_files:
    bio: "Dataset/bio.csv"
    microbes: "Dataset/microbes.csv"
    gut_health: "Dataset/gut_health_test.csv"

# Target Variable Configuration
TARGET_CONFIG:
  target_column: "ccr"
  nutrient_columns:
    - "net_carbs"
    - "protein" 
    - "fat"
    - "fiber"
  remove_after_computation: true

# Feature Engineering Configuration
FEATURE_CONFIG:
  glucose_features:
    enable: true
    rolling_window: 5
    percentiles: [25, 50, 75]
  
  activity_features:
    enable: true
    heart_rate_zones:
      rest: 100
      moderate: 140
      vigorous: 180
  
  microbiome_features:
    enable: true
    pca_components: 10
    diversity_metrics: ["shannon", "simpson", "richness"]
  
  temporal_features:
    enable: true
    meal_times:
      breakfast: [6, 10]
      lunch: [11, 15] 
      dinner: [17, 21]
  
  interaction_features:
    enable: true
    max_interactions: 10

# Model Configuration
MODEL_CONFIG:
  random_state: 42
  test_size: 0.2
  cross_validation_folds: 5
  
  baseline_models:
    linear_regression:
      enable: true
    ridge:
      enable: true
      alpha: 1.0
    lasso:
      enable: true
      alpha: 0.1
      max_iter: 1000
    elastic_net:
      enable: true
      alpha: 0.1
      l1_ratio: 0.5
      max_iter: 1000
  
  intermediate_models:
    random_forest:
      enable: true
      n_estimators: 100
      max_depth: 10
      min_samples_split: 5
      min_samples_leaf: 2
      n_jobs: -1
    
    xgboost:
      enable: true
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      n_jobs: -1
  
  advanced_models:
    lightgbm:
      enable: true
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      n_jobs: -1
      verbose: -1

# Evaluation Configuration
EVALUATION_CONFIG:
  primary_metric: "nrmse"
  secondary_metrics: ["correlation", "r2", "mae"]
  
  outlier_detection:
    iqr_multiplier: 1.5
  
  performance_ranges:
    ccr_low: [0.0, 0.33]
    ccr_mid: [0.33, 0.67] 
    ccr_high: [0.67, 1.0]

# Visualization Configuration
VISUALIZATION_CONFIG:
  save_plots: true
  plot_format: "png"
  plot_dpi: 300
  plot_style: "default"
  color_palette: "husl"
  
  plots_to_generate:
    - "target_distribution"
    - "correlation_heatmap"
    - "missing_data"
    - "model_performance_comparison"
    - "feature_importance"
    - "prediction_vs_actual"
    - "residual_analysis"
    - "model_rankings"

# Output Configuration
OUTPUT_CONFIG:
  results_dir: "results"
  models_dir: "models" 
  reports_dir: "results"
  
  save_formats:
    data: ["csv"]
    models: ["joblib"]
    plots: ["png", "pdf"]
    reports: ["md", "html"]

# Logging Configuration
LOGGING_CONFIG:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "pipeline.log"
  console_output: true

# Performance Configuration
PERFORMANCE_CONFIG:
  n_jobs: -1  # Use all available cores
  memory_limit: "8GB"
  chunk_size: 10000
  
  optimization:
    feature_selection: true
    hyperparameter_tuning: false  # Set to true for grid search
    early_stopping: true

# Validation Configuration
VALIDATION_CONFIG:
  participant_aware_split: true
  time_series_split: false
  stratified_split: false
  
  validation_metrics:
    - "nrmse"
    - "correlation"
    - "r2"
    - "mae"
    - "mse"

# Data Quality Configuration
DATA_QUALITY_CONFIG:
  missing_data_threshold: 0.8  # Drop features with >80% missing
  variance_threshold: 0.0  # Drop zero-variance features
  correlation_threshold: 0.95  # Drop highly correlated features
  
  outlier_handling:
    method: "iqr"  # Options: "iqr", "zscore", "isolation_forest"
    action: "cap"  # Options: "remove", "cap", "transform"

# Reproducibility Configuration
REPRODUCIBILITY_CONFIG:
  set_random_seeds: true
  random_state: 42
  deterministic_operations: true
  
  version_tracking:
    track_versions: true
    save_environment: true
    git_commit_tracking: true